### ISSUE TITLE
Cant run the project

### ISSUE THREAD

**Issue by tamirboker** [mohamedajmaltm/react-shopping-cart#1]
Hello.
I downloaded the project and followed the setup but couldn't run the site.
When i ran 'npm install' on the main folder it threw errors so I tried to run it on the client folder and it worked but 'npm run dev' didn't work on either folder - "npm ERR! missing script: dev".
When I tried 'npm start' on the client folder it almost ran but the site crashed and sent this message: "Proxy error: Could not proxy request /api/products from localhost:3000 to http://localhost:8080/."
I don't know if the problem is because of me or the program but would really appreciate any help.
Thank you!

**Comment by mohamedajmaltm** [comment]
I use 'yarn' as a package manager. I forgot to update the README.

Install yarn by 'npm install --global yarn' or https://yarnpkg.com/en/docs/install (latest version).
Then use 'yarn dev' to start.

**Comment by tamirboker** [comment]
Is it possible to still use the npm package?

**Comment by mohamedajmaltm** [comment]
Remove yarn.lock in both root folder and client folder.
Then run 'npm install' in both root folder and client folder.

Open two terminals - 
1) Run 'npm start' in root folder.
2) Run 'npm start' in client folder.

**Comment by tamirboker** [comment]
Ill try it soon, thank you so much for the help!
